# Imports

In [1]:
import numpy as np

# Algorithm: Gradient Method with Exact Minimization

In [2]:
# from IPython.display import Image
# Image("gradient_method.PNG")
# TODO: Provide details

In [3]:
def gradient_method(x_0, delta, epsilon):
    Q = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, delta]])
    c = np.array([1, 1, 1, 1])
    x = x_0
    k = 0
    while np.linalg.norm(dfunct(Q, c, x)) >= epsilon:
        # print(np.linalg.norm(dfunct(Q, c, x)))
        # print(k)
        descent_direction = -1 * dfunct(Q, c, x)

        step_size = exact_minimization(Q, c, x, descent_direction)

        # update step
        x = x + step_size * descent_direction

        k += 1

    print('Final parameters are \n'
          'x => {x}\n'
          'iterations => {k}\n'
          'delta => {delta}\n'
          'Q => \n {Q}'.format(x=x,
                               k=k,
                               delta=delta,
                               Q=Q))

# Step Size: Exact Minimization Rule for strongly convex quadratics

In [4]:
# TODO: Provide details

In [5]:
def exact_minimization(Q, c, x, d):
    g = dfunct(Q, c, x)
    return -1 * g.T.dot(d) / d.T.dot(Q).dot(d)

# Strongly Convex Quadratic Function

In [6]:
# TODO: Provide more detail

In [7]:
def funct(Q, c, x, gamma):
    return 0.5 * x.T.dot(Q).dot(x) + c + gamma


def dfunct(Q, c, x):
    return Q.dot(x) + c

# Example

In [8]:
deltas = [0.1, 0.01, 0.001, 0.0001, 0.00001, 0.000001]
for delta in deltas:
    gradient_method(x_0=np.array([1, 2, 3, 4]),
                    delta=delta,
                    epsilon=0.00001)

Final parameters are 
x => [-1.00000051 -1.00000076 -1.00000101 -9.99994747]
iterations => 23
delta => 0.1
Q => 
 [[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0.1]]
Final parameters are 
x => [ -1.00000067  -1.000001    -1.00000134 -99.99906642]
iterations => 91
delta => 0.01
Q => 
 [[1.   0.   0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   0.01]]
Final parameters are 
x => [  -1.00000067   -1.000001     -1.00000134 -999.99035134]
iterations => 761
delta => 0.001
Q => 
 [[1.    0.    0.    0.   ]
 [0.    1.    0.    0.   ]
 [0.    0.    1.    0.   ]
 [0.    0.    0.    0.001]]
Final parameters are 
x => [-1.00000068e+00 -1.00000101e+00 -1.00000135e+00 -9.99990196e+03]
iterations => 7449
delta => 0.0001
Q => 
 [[1.e+00 0.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+00 0.e+00 0.e+00]
 [0.e+00 0.e+00 1.e+00 0.e+00]
 [0.e+00 0.e+00 0.e+00 1.e-04]]
Final parameters are 
x => [-1.00000068e+00 -1.00000102e+00 -1.00000136e+00 -9.99990169e+04]
iterations